version: '3.8'

services:
    database:
        image: postgres:15-alpine
        container_name: symfony_db
        environment:
            POSTGRES_DB: symfony_db
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: symfony_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - database

    mailpit:
        image: axllent/mailpit:latest
        container_name: symfony_mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        volumes:
            - mailpit_data:/data
        environment:
            MP_DATA_FILE: /data/mailpit.db
            MP_MAX_MESSAGES: 500


volumes:
    db_data:
    mailpit_data:
